from .connection import get_conn
from .schema import create_tables

from .players import (
    ensure_player,
    get_player,
    add_points,
    record_correct_answer,
    record_wrong_answer,
    increment_games_played,
    increment_games_won,
    get_top_players,
    get_player_rank,
    add_manual_points,
    get_player_profile,
    get_global_leaderboard,
    get_global_leaderboard_page,
    get_player_global_rank_info,
    get_daily_leaderboard_page,
    get_weekly_leaderboard_page,
    get_monthly_leaderboard_page,
    get_player_daily_rank_info,
    get_player_weekly_rank_info,
    get_player_monthly_rank_info,
    get_all_user_ids,
    get_total_users_count,
    get_total_players,
)

from .questions import (
    add_question,
    question_exists,
    get_all_questions,
    get_question_by_id,
    update_question,
    delete_question,
    activate_question,
    deactivate_question,
    get_random_question,
    list_questions,
    get_question_count,
    get_total_questions_count,
)

from .games import (
    ensure_chat,
    deactivate_chat,
    get_all_chat_ids,
    ensure_group_player,
    add_group_points,
    record_group_correct_answer,
    record_group_wrong_answer,
    increment_group_games_played,
    increment_group_games_won,
    get_group_leaderboard,
    get_group_leaderboard_page,
    get_group_daily_leaderboard,
    get_group_weekly_leaderboard,
    get_group_monthly_leaderboard,
    get_player_group_rank_info,
    create_game,
    finish_game,
    record_game_result,
    get_total_games,
    get_total_groups,
    get_broadcast_chat_ids,
    has_played_daily_quiz,
    record_daily_quiz_attempt,
)

__all__ = [
    "get_conn",
    "create_tables",

    "ensure_player",
    "get_player",
    "add_points",
    "record_correct_answer",
    "record_wrong_answer",
    "increment_games_played",
    "increment_games_won",
    "get_top_players",
    "get_player_rank",
    "add_manual_points",
    "get_player_profile",
    "get_global_leaderboard",
    "get_global_leaderboard_page",
    "get_player_global_rank_info",
    "get_daily_leaderboard_page",
    "get_weekly_leaderboard_page",
    "get_monthly_leaderboard_page",
    "get_player_daily_rank_info",
    "get_player_weekly_rank_info",
    "get_player_monthly_rank_info",
    "get_all_user_ids",
    "get_total_users_count",
    "get_total_players",

    "add_question",
    "question_exists",
    "get_all_questions",
    "get_question_by_id",
    "update_question",
    "delete_question",
    "activate_question",
    "deactivate_question",
    "get_random_question",
    "list_questions",
    "get_question_count",
    "get_total_questions_count",

    "ensure_chat",
    "deactivate_chat",
    "get_all_chat_ids",
    "ensure_group_player",
    "add_group_points",
    "record_group_correct_answer",
    "record_group_wrong_answer",
    "increment_group_games_played",
    "increment_group_games_won",
    "get_group_leaderboard",
    "get_group_leaderboard_page",
    "get_group_daily_leaderboard",
    "get_group_weekly_leaderboard",
    "get_group_monthly_leaderboard",
    "get_player_group_rank_info",
    "create_game",
    "finish_game",
    "record_game_result",
    "get_total_games",
    "get_total_groups",
    "get_broadcast_chat_ids",
    "has_played_daily_quiz",
    "record_daily_quiz_attempt",
]