from .connection import get_conn
from .schema import create_tables

from .questions import (
    normalize_correct_option,
    correct_option_to_letter,
    normalize_question_text,
    question_exists,
    add_question,
    get_random_question,
    list_questions,
    get_all_questions,
    get_question_by_id,
    update_question,
    deactivate_question,
    activate_question,
    delete_question,
    get_question_count,
    get_total_questions_count,
)

from .players import (
    ensure_player,
    get_player,
    add_points,
    record_correct_answer,
    record_wrong_answer,
    increment_games_played,
    increment_games_won,
    get_top_players,
    get_player_rank,
    add_manual_points,
    get_player_profile,
    get_global_leaderboard,
    get_global_leaderboard_page,
    get_player_global_rank_info,
    get_all_user_ids,
    get_total_users_count,
    get_total_players,
)

from .games import (
    ensure_chat,
    deactivate_chat,
    get_all_chat_ids,
    add_group_points,
    record_group_correct_answer,
    increment_group_games_played,
    increment_group_games_won,
    get_group_leaderboard,
    get_group_leaderboard_page,
    get_player_group_rank_info,
    create_game,
    finish_game,
    record_game_result,
    get_total_games,
    get_total_groups,
    get_broadcast_chat_ids,
    has_played_daily_quiz,
    record_daily_quiz_attempt,
)