ADMIN_MENU, QUESTION, A, B, C, D, CORRECT = range(7)

DELETE_ID, DELETE_CONFIRM = range(7, 9)

EDIT_ID, EDIT_QUESTION, EDIT_A, EDIT_B, EDIT_C, EDIT_D, EDIT_CORRECT, EDIT_CATEGORY, EDIT_DIFFICULTY = range(9, 18)

BROADCAST_MESSAGE, BROADCAST_CONFIRM = range(18, 20)

IMPORT_FILE = 20
SEARCH_KEYWORD = 21

EDIT_TEXT_ONLY = 22
EDIT_OPTION_ONLY = 23
EDIT_CORRECT_ONLY = 24
EDIT_CATEGORY_ONLY = 25
EDIT_DIFFICULTY_ONLY = 26

SETTING_VALUE = 1000
GROUP_SEARCH = 999